<?php

namespace App\Http\Controllers;

use App\Http\Requests\DeviceLoginRequest;
use App\Http\Requests\LinkAccountRequest;
use App\Http\Requests\loginRequest;
use App\Http\Requests\RegisterRequest;
use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;
use App\Mail\OtpMail;

class AuthController extends Controller
{
    public function deviceLogin(DeviceLoginRequest $request)
    {
        $validated = $request->validated();
        $user = User::firstOrCreate(['device_id' => $validated['device_id']], [
            'username' => 'User'.time(),
        ]);

        $token = $user->createToken('device_token')->plainTextToken;

        return $this->success([
            'user' => new UserResource($user),
            'token' => $token,
        ], 'Logged in successfully');
    }

    public function register(RegisterRequest $request)
    {
        $validated = $request->validated();

        $user = User::create([
            'username' => $validated['username'],
            'email' => $validated['email'],
            'password' => Hash::make($validated['password']),
            'device_id' => $validated['device_id'], // TODO: device id should be generated by the client

        ]);
        $otp = rand(100000, 999999);
    Cache::put('otp_' . $user->email, $otp, now()->addMinutes(10));
    Mail::to($user->email)->send(new OtpMail($otp));

        $token = $user->createToken('device_token')->plainTextToken;

    //     return $this->success([
    //         'user' => new UserResource($user),
    //         'token' => $token,
    //     ], 'User registered successfully');
    return $this->success(['token' => $token], 'User registered successfully. Please check your email for the OTP code.');
    }

    public function LinkAccount(LinkAccountRequest $request)
    {
        $user = $request->user();
        if ($user->email) {
            return $this->error('Account already linked to an email', 400);
        }

        $validateduser = $request->validated();

        $user->update([
            'email' => $validateduser['email'],
            'password' => Hash::make($validateduser['password']),
            'provider_id' => $validateduser['provider_id'] ?? $user->provider_id,
        ]);


        $otp = rand(100000, 999999);

    // بنخزن البيانات اللي اللاعب عايز يربطها مؤقتاً في الكاش مع الكود
    Cache::put('link_data_' . $user->id, [
        'email' => $validateduser['email'],
        'password' => $validateduser['password'],
        'otp' => $otp
    ], now()->addMinutes(10));

    // إرسال الكود للإيميل الجديد اللي عايز يربط بيه
    Mail::to($validateduser['email'])->send(new OtpMail($otp));

    return $this->success(null, 'OTP sent to verify your new email.');

        // return $this->success(['user' => new UserResource($user)], 'Account linked successfully');
    }










public function verifyOtp(Request $request)
{
    $request->validate([
        'email' => 'required|email',
        'otp' => 'required|numeric',
        'type' => 'required|in:register,link' // عشان نعرف إحنا بنتحقق من إيه
    ]);

    $cachedOtp = Cache::get('otp_' . $request->email);

    if ($request->type == 'register') {
        if ($cachedOtp && $cachedOtp == $request->otp) {
            $user = User::where('email', $request->email)->first();
            $token = $user->createToken('user_token')->plainTextToken;
            Cache::forget('otp_' . $request->email); // مسح الكود بعد الاستخدام

            return $this->success(['user' => new UserResource($user), 'token' => $token], 'Verified successfully');
        }
    } 
    
    if ($request->type == 'link') {
        if (!$request->user()) {
        return $this->error('Unauthorized', 401);
    }
        $linkData = Cache::get('link_data_' . $request->user()->id);
        
        if ($linkData && $linkData['otp'] == $request->otp && $linkData['email'] == $request->email) {
            $request->user()->update([
                'email' => $linkData['email'],
                'password' => Hash::make($linkData['password']),
            ]);
            Cache::forget('link_data_' . $request->user()->id);

            return $this->success(['user' => new UserResource($request->user())], 'Account linked successfully');
        }
    }

    return $this->error('Invalid or expired OTP', 422);
}
















    public function login(LoginRequest $request)
    {
        $validated = $request->validated();

        $user = User::where('email', $validated['email'])->first();
        if (! $user || ! Hash::check($validated['password'], $user->password)) {
            return $this->error('Invalid credentials', 401);
        }

        $token = $user->createToken('user_token')->plainTextToken;

        return $this->success([
            'user' => new UserResource($user),
            'token' => $token,
        ], 'Logged in successfully');
    }

    public function logout(Request $request)
    {
        $request->user()->tokens()->delete();

        return $this->success(null, 'Logged out successfully');
    }

    public function handleProviderCallback($provider)
    {
        $socialUser = Socialite::driver($provider)->user();
        $user = User::firstOrCreate(
            ['email' => $socialUser->getEmail()],
            [
                'username' => $socialUser->getName(),
                'provider_id' => $socialUser->getId(),
                'provider_name' => $provider,
                'avatar' => $socialUser->getAvatar(),

            ]
        );

        $token = $user->createToken('auth_token')->plainTextToken;

        return $this->success(['token' => $token, 'user'    => new UserResource($user),]);
      
    }
}
