<?php

namespace App\Http\Controllers;

use App\Http\Requests\DeviceLoginRequest;
use App\Http\Requests\LinkAccountRequest;
use App\Http\Requests\loginRequest;
use App\Http\Requests\RegisterRequest;
use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;

class AuthController extends Controller
{
    public function deviceLogin(DeviceLoginRequest $request)
    {
        $validated = $request->validated();
        $user = User::firstOrCreate(['device_id' => $request->$validated['device_id']], [
            'username' => 'User'.time(),
        ]);

        $token = $user->createToken('device_token')->plainTextToken;

        return $this->success([
            'user' => new UserResource($user),
            'token' => $token,
        ], 'Logged in successfully');
    }

    public function register(RegisterRequest $request)
    {
        $validated = $request->validated();

        $user = User::create([
            'username' => $validated['username'],
            'email' => $validated['email'],
            'password' => Hash::make($validated['password']),
            'device_id' => Str::random(32), // TODO: device id should be generated by the client

        ]);

        $token = $user->createToken('device_token')->plainTextToken;

        return $this->success([
            'user' => new \App\Http\Resources\UserResource($user),
            'token' => $token,
        ], 'User registered successfully');
    }

    public function LinkAccount(LinkAccountRequest $request)
    {
        $user = $request->user();
        if ($user->email) {
            return $this->error('Account already linked to an email', 400);
        }

        $validateduser = $request->validated();

        $user->update([
            'email' => $validateduser['email'],
            'password' => Hash::make($validateduser['password']),
            'provider_id' => $validateduser['provider_id'] ?? $user->provider_id,
        ]);

        return $this->success(['user' => new \App\Http\Resources\UserResource($user)], 'Account linked successfully');
    }

    public function login(LoginRequest $request)
    {
        $validated = $request->validated();

        $user = User::where('email', $validated['email'])->first();
        if (! $user || ! Hash::check($validated['password'], $user->password)) {
            return $this->error('Invalid credentials', 401);
        }

        $token = $user->createToken('device_token')->plainTextToken;

        return $this->success([
            'user' => new \App\Http\Resources\UserResource($user),
            'token' => $token,
        ], 'Logged in successfully');
    }

    public function logout(Request $request)
    {
        $request->user()->tokens()->delete();

        return $this->success(null, 'Logged out successfully');
    }

    public function handleProviderCallback($provider)
    {
        $socialUser = Socialite::driver($provider)->user();
        $user = User::firstOrCreate(
            ['email' => $socialUser->getEmail()],
            [
                'username' => $socialUser->getName(),
                'provider_id' => $socialUser->getId(),
                'provider_name' => $provider,
                'avatar' => $socialUser->getAvatar(),

            ]
        );

        $token = $user->createToken('auth_token')->plainTextToken;

        return $this->success(['token' => $token, 'user' => new \App\Http\Resources\UserResource($user)]);
    }
}
